"""collection items

Revision ID: e012786f44af
Revises: 34b85184db17
Create Date: 2025-11-10 18:13:34.700066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e012786f44af'
down_revision: Union[str, Sequence[str], None] = '34b85184db17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pokemon_id', name='uq_user_pokemon')
    )
    op.create_index(op.f('ix_collection_items_id'), 'collection_items', ['id'], unique=False)
    op.create_index(op.f('ix_collection_items_pokemon_id'), 'collection_items', ['pokemon_id'], unique=False)
    op.create_index(op.f('ix_collection_items_user_id'), 'collection_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_items_user_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_pokemon_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_id'), table_name='collection_items')
    op.drop_table('collection_items')
    # ### end Alembic commands ###
